# ~/.config/starship.toml

# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "ğŸ”Œ"
# discharging_symbol = "âš¡"

[[battery.display]]
threshold = 20

# [character]
# error_symbol = "[âœ–](bold red) "

[cmd_duration]
min_time = 100  # given in milliseconds
format = "took [$duration]($style)"

[directory]
truncation_length = 2
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
# format = " [$symbol$branch]($style) "
# symbol = "ğŸ£ "
# style = "bold yellow"

[git_commit]
# commit_hash_length = 8
# style = "bold white"

[git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
# conflicted = "âš”ï¸ "
# ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
# behind = "ğŸ¢ Ã—${count}"
# diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "âšªï¸ "
stashed = "ğŸŸ¤ "
modified = "ğŸŸ  "
staged = "ğŸŸ¢ "
renamed = "ğŸŸ  "
deleted = "ğŸ”´i "
# format = "$all_status$ahead_behind"
format = "$all_status"

[hostname]
# ssh_only = false
# format = "<[$hostname]($style)>"
# trim_at = "-"
# style = "bold dimmed white"
# disabled = true

[julia]
# format = "[$symbol$version]($style) "
# symbol = "à®ƒ "
# style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 75
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
# format = "[$symbol$version]($style) "
# style = "bold green"

[rust]
# format = "[$symbol$version]($style) "
# style = "bold green"

[time]
# # time_format = "%T"
# # format = "ğŸ•™ $time($style) "
# # style = "bright-white"
# # disabled = false

[username]
# style_user = "bold dimmed blue"
# style_user = "red"
show_always = true

[nodejs]
# # format = "via [ğŸ¤– $version](bold green) "
